# starship
# https://starship.rs/
# ã‚·ãƒ³ãƒœãƒªãƒƒã‚¯ãƒªãƒ³ã‚¯ã‚’è²¼ã‚‹
# ln -s (ped)/starship.toml ~/.config/starship.toml

[memory_usage]
disabled = false
format = 'via $symbol [${ram_pct}( | ${swap_pct})]($style) '
threshold = -1
symbol = 'MEM'
style = 'bold dimmed green'

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸ‘†${count}'
behind = 'ğŸ‘‡${count}'
diverged = 'ğŸ‘†${ahead_count}ğŸ‘‡${behind_count}'
up_to_date = ''
untracked = 'ğŸ¤·'
stashed = ''
modified = '[M\($count\)](yellow)'
staged = '[++\($count\)](green)'
renamed = '[R\($count\)](yellow)'
deleted = '[D\($count\)](red)'

# ã‚³ãƒãƒ³ãƒ‰å®Ÿè¡Œã«5ç§’ä»¥ä¸Šã‹ã‹ã£ãŸå ´åˆã«è¡¨ç¤º
[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

[docker_context]
disabled = true

[golang]
format = 'via [Go $version](bold cyan) '
